# Generated by Django 4.2.6 on 2023-10-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.collection'),
        ),
    ]
